### ISSUE TITLE
Same here: I get: could not get cookie. Started yesterday. Windows-7 64Bit.

### ISSUE THREAD

**Issue by alon-a** [adrianmichel/yloader#17]

**Comment by pinotin** [comment]
I get: could not get cookie. Started yesterday. Windows 10 64Bit.

**Comment by B-i-l-l-A** [comment]
Previously reported. See "https://github.com/adrianmichel/yloader/issues/16".
Suggest you subscribe to notifications on that thread.

**Comment by adrianmichel** [comment]
Sorry for the long delay. I'm looking into the issue.

**Comment by FelixvdLM** [comment]
That’s great! Many thanks!

 

Von: Adrian Michel ***@***.*** 
Gesendet: Dienstag, 30. August 2022 00:09
An: adrianmichel/yloader
Cc: FelixvdLM; Manual
Betreff: Re: [adrianmichel/yloader] Same here: I get: could not get cookie. Started yesterday. Windows-7 64Bit. (Issue #17)

 

Closed #17 <https://github.com/adrianmichel/yloader/issues/17>  as completed.
