### ISSUE TITLE
failed to create empty document

### ISSUE THREAD

**Issue by densma1** [adrianmichel/yloader#18]
all of a sudden I'm getting this error "failed to create empty document" i can't run the application.
any ideas?

**Comment by adrianmichel** [comment]
Sorry for the delay. Is it still happening?

**Comment by densma1** [comment]
Yes. I notice  restarting the computer works. If I run it now, next time error occurs or wont be able to run again unless i restart  or reinstall  dot net 3.5 again

**Comment by adrianmichel** [comment]
YLoader doesn't depend on .Net, so I'm not sure what the issue is. Closing.
