### ISSUE TITLE
Yloader no longer downloads data from yahoo

### ISSUE THREAD

**Issue by Frenk71** [adrianmichel/yloader#19]
Good morning

I have been using your software for about a year to update stock data and I find it very efficient and useful.
For some time the software has not been able to download the data giving the following message: COULD NOT GET COOKIE.
Probably some settings have changed from yahoo but I can't solve the problem.

can you help me please

**Comment by B-i-l-l-A** [comment]
Previously reported. See "https://github.com/adrianmichel/yloader/issues/16".
Suggest you subscribe to notifications on that thread.

**Comment by toddao** [comment]
from 6/5/2022
"Notes from merchant" :
I'm sorry for delay with updating uploader for the Yahoo changes, I'm however in a middle of a personal situation that is making it very difficult for me to focus on other things. I'll work on it as soon as I can. Best, Adrian

**Comment by toddao** [comment]
I'm just going to make do until Adrian gets back.  If anyone has any good ideas for **bulk** updating until then it would be great if you mentioned it here.  Thanks

**Comment by toddao** [comment]
August 12th.......... time to give up on yloader update..............sad

**Comment by nkormanik** [comment]
Adrian will come through.  Please direct positive thoughts his way.

**Comment by toddao** [comment]
I had an excel spreadsheet fixed that downloads from yahoo.  It
required one code line of remove and replace.

yloader is open source, if someone can tell me what kind of programmer
I need to do that to Adrian's work  I will take care of it and cover
the cost.  

Yloader is much more elegant then my spreadsheet.

I am a trader, relying on wishful thinking is a mistake.

**Comment by nkormanik** [comment]
Amen to all that.  But, positive thoughts do make a difference.

I primarily focus on just a single security -- SPY.

Yloader so efficiently downloaded SPY daily, using Windows task manager.  Wonderful little program.

The best alternative I've found is to download data from Stooq:

https://stooq.com/db/h/

Can't simply download SPY, however.  Have to download a huge bundle, every evening.

Another approach seems to be to use an API.  Many sites are providing this.  However, I haven't been able to figure out how to efficiently go about it.

**Comment by adrianmichel** [comment]
Sorry for the long delay. I'm looking into the issue.

**Comment by nkormanik** [comment]
Glad to hear that, Adrian.  Hopefully it will be a rather minor tweak that's needed.  Please tell us what you find.

**Comment by adrianmichel** [comment]
I've committed changes for a possible fix. I have uploaded the installer at https://yloader.com/download/6.0/0.6/y6_64_setup.exe . Please try it and let me know of any issues.
